### ISSUE TITLE
Posibility to find yeelight on other network

### ISSUE THREAD

**Issue by Quisoor** [NicolasD-62/gladys-yeelight#1]
When you use Gladys in **docker**, the container no have **the same network** of yeelight and the module don't find them.

Exemple :

- Gladys container network = 172.17.0.0
- Local network = 192.168.0.0

**Comment by NicolasD-62** [comment]
It's not a module probleme, but a docker one.
You need to translate container network IP to an external one.

Maybe you can find what youy need here : 
http://blog.oddbit.com/2014/08/11/four-ways-to-connect-a-docker/
